import Link from "next/link";import { notFound } from "next/navigation";
import { Beta2FounderAccessError,getBeta2Dashboard,getFounderBeta2Feedback,pseudonymousParticipantId } from "@/core/beta2/server";
const pct=(v:number|null)=>v===null?"—":`${Math.round(v*100)}%`;const money=(v:number|null)=>v===null?"—":`$${v.toFixed(2)}`;
export default async function Beta2Page(){let data;let feedback;try{[data,feedback]=await Promise.all([getBeta2Dashboard(),getFounderBeta2Feedback()]);}catch(error){if(error instanceof Beta2FounderAccessError)notFound();throw error;}
 const s=data.summary;return <main className="min-h-screen bg-[#07070d] p-6 text-white"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs uppercase tracking-widest text-violet-300">Founder only · Measured Beta 2</p><h1 className="mt-2 text-3xl font-semibold">Beta 2 operations</h1><p className="mt-2 text-zinc-400">Cohort state is operational; analytics never grants access. Targets are hypotheses, not automatic verdicts.</p><a href="/api/founder/beta-2/export" className="mt-3 inline-block text-sm text-violet-300">Export privacy-safe CSV</a></header>
 <section className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Invited",s.invited],["Joined",s.joined],["Activated",s.activated],["D1",s.d1],["D7",s.d7],["Completed",s.completed]].map(([k,v])=><div key={k} className="rounded-xl border border-white/10 p-4"><span className="text-xs text-zinc-500">{k}</span><strong className="mt-1 block text-2xl">{v}</strong></div>)}</section>
 <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Invite → signup",pct(s.inviteToSignupRate)],["Signup → intent",pct(s.signupToIntentRate)],["Intent → project",pct(s.intentToProjectRate)],["Project → result",pct(s.projectToResultRate)],["Activation",pct(s.activationRate)],["Median Aha",s.medianMinutesToActivation===null?"—":`${s.medianMinutesToActivation.toFixed(1)} min`],["Cost / activated",money(s.costPerActivatedUser)],["Unresolved feedback",s.unresolvedFeedback]].map(([k,v])=><div key={k} className="rounded-xl border border-white/10 p-4"><span className="text-xs text-zinc-500">{k}</span><strong className="mt-1 block">{v}</strong></div>)}</section>
 <div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-white/[.04] text-zinc-400"><tr>{["Participant","Status","Intent","Project","Activated","D1","D7","Milestones","Last session","AI cost","Unpriced","Failures","Abandonment"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.participants.map(p=><tr key={p.userId} className="border-t border-white/10"><td className="p-3" title={p.email??undefined}>{pseudonymousParticipantId(p.userId)}</td><td className="p-3">{p.status}</td><td className="p-3">{p.firstIntentAt?"Yes":"No"}</td><td className="p-3">{p.projectCreatedAt?"Yes":"No"}</td><td className="p-3">{p.minutesToActivation===null?"—":`${p.minutesToActivation.toFixed(1)}m`}</td><td className="p-3">{p.d1?"Yes":"No"}</td><td className="p-3">{p.d7?"Yes":"No"}</td><td className="p-3">{p.milestones.length}/7</td><td className="p-3">{p.lastMeaningfulAt?.slice(0,10)??"—"}</td><td className="p-3">{money(p.aiCostUsd)}</td><td className="p-3">{p.unpricedOperations}</td><td className="p-3">{p.failedOperations}</td><td className="p-3">{p.abandonment??"—"}</td></tr>)}</tbody></table></div>
 <section><h2 className="text-xl font-semibold">Feedback &amp; unresolved issues</h2><div className="mt-3 space-y-2">{feedback.map(item=><article key={item.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap gap-2 text-xs text-zinc-400"><span>{item.kind}</span><span>{item.category}</span><span>{item.severity??"UNTRIAGED"}</span><span>{item.resolvedAt?"RESOLVED":"OPEN"}</span><span>{pseudonymousParticipantId(item.participantUserId)}</span></div>{item.text?<p className="mt-2 whitespace-pre-wrap text-sm">{item.text}</p>:null}</article>)}</div>{!feedback.length?<p className="mt-2 text-sm text-zinc-500">No Beta 2 feedback yet.</p>:null}</section>
 <footer className="flex gap-4 text-sm"><Link href="/iaura/beta-usage" className="text-violet-300">Legacy beta operations</Link><Link href="/iaura/usage-cost" className="text-violet-300">Detailed AI cost</Link></footer></div></main>}
