create table public.beta_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  event_type text not null check (event_type in (
    'beta_signed_in', 'project_opened', 'project_created',
    'message_sent', 'beta_step_completed'
  )),
  project_id text,
  event_key text,
  metadata jsonb not null default '{}'::jsonb check (
    jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 2048
  ),
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index beta_usage_events_user_created_idx
  on public.beta_usage_events (user_id, created_at desc);

alter table public.beta_usage_events enable row level security;

create policy beta_usage_events_insert_own
on public.beta_usage_events
for insert to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.beta_usage_events from anon, authenticated;
grant insert (user_id, event_type, project_id, event_key, metadata)
on table public.beta_usage_events to authenticated;

create or replace function public.founder_beta_usage()
returns table (
  user_id uuid,
  email text,
  display_name text,
  joined_at timestamptz,
  account_created_at timestamptz,
  last_sign_in_at timestamptz,
  last_active_at timestamptz,
  project_count bigint,
  conversation_count bigint,
  user_message_count bigint,
  latest_milestone text,
  usage_status text,
  evidence_source text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.beta_memberships
    where beta_memberships.user_id = auth.uid()
      and role = 'founder' and status = 'active'
  ) then
    raise exception 'Founder access required' using errcode = '42501';
  end if;

  return query
  with project_activity as (
    select p.user_id, count(*)::bigint as project_count, max(p.updated_at) as last_project_at
    from public.projects p group by p.user_id
  ), conversation_activity as (
    select cs.user_id,
      count(distinct (c.item ->> 'conversationId'))::bigint as conversation_count,
      count(m.item) filter (where m.item ->> 'role' = 'user')::bigint as user_message_count,
      max(nullif(m.item ->> 'createdAt', '')::timestamptz) as last_message_at,
      max(c.item #>> '{betaWorkflow,status}') as inferred_milestone
    from public.conversation_state cs
    left join lateral jsonb_array_elements(coalesce(cs.data -> 'conversations', '[]'::jsonb)) c(item) on true
    left join lateral jsonb_array_elements(coalesce(c.item -> 'messages', '[]'::jsonb)) m(item) on true
    group by cs.user_id
  ), event_activity as (
    select e.user_id, count(*)::bigint as event_count,
      count(distinct e.created_at::date)::bigint as active_days,
      min(e.created_at) as first_event_at, max(e.created_at) as last_event_at,
      (array_agg(coalesce(e.metadata ->> 'milestone', e.event_type)
        order by e.created_at desc))[1] as latest_event
    from public.beta_usage_events e group by e.user_id
  )
  select bm.user_id, au.email::text, p.display_name, bm.claimed_at,
    au.created_at, au.last_sign_in_at,
    greatest(au.last_sign_in_at, pa.last_project_at, ca.last_message_at, ea.last_event_at),
    coalesce(pa.project_count, 0), coalesce(ca.conversation_count, 0),
    coalesce(ca.user_message_count, 0),
    coalesce(ea.latest_event, ca.inferred_milestone,
      case when coalesce(pa.project_count, 0) > 0 then 'project_created' end,
      case when au.last_sign_in_at is not null then 'beta_signed_in' end),
    case
      when coalesce(ea.active_days, 0) >= 2
        or au.last_sign_in_at > au.created_at + interval '1 day' then 'returned'
      when coalesce(ca.user_message_count, 0) > 0 and coalesce(pa.project_count, 0) > 0 then 'active'
      when coalesce(ca.user_message_count, 0) > 0 then 'started'
      when au.last_sign_in_at is not null or coalesce(ea.event_count, 0) > 0 then 'entered'
      else 'joined'
    end,
    case when coalesce(ea.event_count, 0) > 0 then 'explicit'
      when au.last_sign_in_at is not null or coalesce(pa.project_count, 0) > 0
        or coalesce(ca.user_message_count, 0) > 0 then 'inferred'
      else 'none' end
  from public.beta_memberships bm
  join auth.users au on au.id = bm.user_id
  left join public.profiles p on p.id = bm.user_id
  left join project_activity pa on pa.user_id = bm.user_id
  left join conversation_activity ca on ca.user_id = bm.user_id
  left join event_activity ea on ea.user_id = bm.user_id
  order by last_active_at desc nulls last, bm.claimed_at desc;
end;
$$;

revoke all on function public.founder_beta_usage() from public, anon;
grant execute on function public.founder_beta_usage() to authenticated;

comment on table public.beta_usage_events is
  'Minimal private-beta telemetry. Never stores message, prompt, response, or memory content.';
